Fix stuff
ANF-Studios/WinPath pull request #41
Opened 2021-04-29 13:54 UTC by l-7777777

Fixed some various stuff (mostly beatifying) and realized that [this issue](https://github.com/ANF-Studios/WinPath/issues/32) wasn't an issue at all.

2021-04-29 14:13 UTC, ANF-Studios commented on .gitignore
> +.vscode
I prefer not to ignore `.vscode`

2021-04-29 14:14 UTC, ANF-Studios commented on WinPath/src/Update.cs
> +        private const string Releases = "https://api.github.com/repos/ANF-Studios/WinPath/releases";
You're violating naming conventions.

2021-04-29 14:19 UTC, l-7777777 commented on WinPath/src/Update.cs
> +                    if (application != null)
in case `application` is null

2021-04-29 14:21 UTC, l-7777777 commented
wait how do I add another commit to this lmao

2021-04-29 14:38 UTC, ANF-Studios commented on WinPath/src/Update.cs
> +                    if (application != null)
I can tell that, I mean tell me a possibility of when/where it's null.

2021-04-30 09:54 UTC, ANF-Studios requested changes
A lot of stuff is wrong.
* Coding and formatting conventions are broken, mostly of the code base.
* You didn't have to even modify the gitignore.
* You committed your idea folder after.. ignoring it..?
* You changed the functionality of already working code that had no flaws.
* You have.. debug code? Of your own pc/config?
* Usings are not in order.
* You are violating C#'s naming conventions.
and more changes that are minor.

I do not approve, revert those changes back please.

2021-04-30 09:54 UTC, ANF-Studios commented on WinPath/src/Program.cs
> +                            @";C:\Users\lysan\AppData\Local\Microsoft\WindowsApps;C:\Users\lysan\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\heroku\bin;C:\Users\lysan\AppData\Roamin
?

2021-04-30 09:54 UTC, ANF-Studios commented on WinPath/src/Program.cs
> +                    if (options != null)
This is not needed.

2021-04-30 17:33 UTC, lylythechosenone commented on WinPath/src/Update.cs
> +                string response;
No, I removed that on purpose. It was unnecessary.

2021-05-12 19:01 UTC, ANF-Studios commented
You were given a some time to implement that however you never did so I'm going to have to close this issue. If you want to discuss this, please reopen this pull request.

2021-05-12 19:01 UTC, closed without merging